job_ingestion_api:
  base_url: "https://jsearch.p.rapidapi.com/search"
  api_host: "jsearch.p.rapidapi.com"
  rate_limit_per_sec: 1.0
  last_request_time: 0.0
  queries:
    - developer
    - designer
    - marketing
    - sales
    - data
    - engineer
    - product

  locations:
    - null
    - remote
    - USA
    - UK
    - Canada
    - Germany

  remote_options:
    - null
    - true
    - false
  total_jobs: 5
  jobs_per_page: 1
  job_local_file_name: "jsearch_jobs_raw.json"
  job_base_path: "data/raw_jobs"
  gcs_prefix: "jobs/jsearch"
  writer_mode: "local"  # options: "local" or "gcs"
  gcs_bucket_name: "two-stage-recommendation-system-data"


user_data_ingestion:
  user_gcs_prefix: "users/synthetic"
  user_gcs_bucket_name: "two-stage-recommendation-system-data"
  user_local_file_name: "users_raw.json"
  user_base_path: "data/users"
  
  experience_levels:
    - junior
    - mid
    - senior

  education_levels:
    - high_school
    - bachelors
    - masters
    - phd

  locations:
    - USA
    - UK
    - Canada
    - Germany
    - remote
  
  writer_mode: "local"  # options: "local" or "gcs"
  random_seed: 42
  total_users: 50
  num_users: 30

