job_ingestion_api:
  base_url: "https://jsearch.p.rapidapi.com/search"
  api_host: "jsearch.p.rapidapi.com"
  rate_limit_per_sec: 1.0
  last_request_time: 0.0
  queries:
    - developer
    - designer
    - marketing
    - sales
    - data
    - engineer
    - product

  locations:
    - null
    - remote
    - USA
    - UK
    - Canada
    - Germany

  remote_options:
    - null
    - true
    - false
  total_jobs: 100
  jobs_per_page: 1
  job_local_file_name: "jsearch_jobs_raw.json"
  job_base_path: "data/raw_jobs"
  job_clean_path: "data/clean_jobs/jobs_clean.json"
  gcs_prefix: "jobs/jsearch"
  writer_mode: "local"  # options: "local" or "gcs"
  gcs_bucket_name: "two-stage-recommendation-system-data"


user_data_ingestion:
  user_gcs_prefix: "users/synthetic"
  user_gcs_bucket_name: "two-stage-recommendation-system-data"
  user_local_file_name: "users_raw.json"
  user_base_path: "data/users"
  
  experience_levels:
    - junior
    - mid
    - senior

  education_levels:
    - high_school
    - bachelors
    - masters
    - phd

  locations:
    - USA
    - UK
    - Canada
    - Germany
    - remote
  
  writer_mode: "local"  # options: "local" or "gcs"
  random_seed: 42
  total_users: 50
  num_users: 30
  user_clean_path: "data/clean_users/users_clean.json"

user_interaction_ingestion:
  interaction_gcs_prefix: "interactions/synthetic" 
  interaction_gcs_bucket_name: "two-stage-recommendation-system-data"
  interaction_local_file_name: "interactions_raw.json"
  interaction_base_path: "data/interactions"
  writer_mode: "local"  # options: "local" or "gcs"
  random_seed: 42 
  interactions_per_user: 10
  interaction_events_type:
    - view
    - click
    - apply
  interaction_events_weights:
    - 0.7
    - 0.2 
    - 0.1
  interaction_seed: 42
  interaction_clean_path: "data/clean_interactions/interactions_clean.json"
  interaction_labeled_path: "data/labeled/labeled.json"
  interaction_policy_path: "src/supervision/policy/labeling_policy.yaml"
  interaction_nagative_sampling_ratio: 3
  interaction_negative_sampling_seed: 42
  negative_sample_path: "data/negative_samples/negative_samples.json"
  interaction_positive_path: "data/positive_samples/positive_samples.json"

model_training:
  user_feature_path: "data/features/user_features.json"
  job_feature_path: "data/features/job_features.json"
  final_dataset_path: "data/features/dataset/final_dataset.json"
  ranking_dataset_path: "data/features/dataset/ranking_dataset.json"
  ranking_dataset_random_seed: 42
  ranking_ds_skill_overlap_range: [0, 1]
  ranking_ds_experience_gap_range: [-5, 5]
  two_tower_dataset_path: "data/datasets/two_tower_dataset.json"
  embed_model_names: "all-MiniLM-L6-v2"
  user_embedding_dim: 783
  job_embedding_dim: 1159
  allowed_labels: [0, 1]
  feast_repo_path: "C:\\Users\\USER\\Desktop\\Two_stage_recommendation_system\\rs_feature_repo\\feature_repo"
  fs_writer_version: "v1"    