artifact_root: artifacts

data_service_config:
  root_dir: artifacts/data
  source_URL: https://github.com/krishnaik06/datasets/raw/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts\data_ingestion\winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt