artifacts_root: artifacts

data_ingestion:

  jobs:
    root_dir: artifacts/data_ingestion/jobs

    source:
      type: api
      provider: jsearch

      queries:
        - developer
        - designer
        - marketing
        - sales
        - data
        - engineer
        - product

      locations:
        - null
        - remote
        - USA
        - UK
        - Canada
        - Germany

    output:
      mode: local
      bronze_path: data/bronze/jobs

  users:
    root_dir: artifacts/data_ingestion/users

    generation:
      num_users: 500
      seed: 42

    output:
      mode: local
      bronze_path: data/bronze/users

  interactions:
    root_dir: artifacts/data_ingestion/interactions

    input:
      users_bronze_path: data/bronze/users
      jobs_bronze_path: data/bronze/jobs

    generation:
      interactions_per_user: 10
      seed: 42

      event_distribution:
        view: 0.7
        click: 0.2
        apply: 0.1

    output:
      mode: local
      bronze_path: data/bronze/interactions
